### ISSUE TITLE
tuning on alpaca dataset

### ISSUE THREAD

**Issue by GeorvityLabs** [jdwx/gptj-finetune#3]
@jdwx , how can we use this repo to fine tune on alpaca dataset (.jsonl file)
could you provide the instructions for that.

thanks.

**Comment by jdwx** [comment]
This repository is for GPT-J. I have never worked with the alpaca model and do not know what would be involved in adapting this code to work with it.  It is based on the LLaMa model, which has some access issues, so even if someone had the Alpaca model weights (which I do not), using them would be more of a can of legal worms than I'm looking to open.
